# This workflow will install Python dependencies and run tests
name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install .
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install copy/paste on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install xsel xclip
        pip install gtk PyQt4

    - name: Test with pytest
      run: |
        pytest --cov=airshare tests